name: Build and Release SO

on:
  push:
  # push:
  #   tags:
  #     - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Check versions
      run: |
        cmake --version
        g++ --version
        which g++
        which cmake

    - name: Install dependencies
      run: sudo apt install -y g++-14 ninja-build

    - name: Check versions2
      run: |
        cmake --version
        ninja --version
        g++ --version
        g++-14 --version
        which g++
        which g++-14
        which cmake
        ls -la /usr/bin/ | grep ++

    - name : Set g++-14 as default
      run: sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 90

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      run: |
        cd build
        cmake .. -G Ninja

    

    - name: Build
      run: |
        cd build
        ninja

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/libmemory.so
        asset_name: libmemory.so
        asset_content_type: application/octet-stream