name: Build and Release SO

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Install dependencies
      run: sudo apt-get install -y g++

    - name: Create build directory
      run: mkdir -p build

    - name: Configure CMake
      run: |
        cd build
        cmake ..

    - name: Build
      run: |
        cd build
        make

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        tag_name: v0.0.1
        release_name: Release v0.0.1
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libmemory.so
        asset_name: libmemory.so
        asset_content_type: application/octet-stream